# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Calypso/Documents/- - - UIUC Academics/Spring 2024/ECE 385/Lab 7/ECE385_Lab7.1/ECE385_Lab7.1.srcs/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_clk_wiz_1_0/Lab7MicroBlaze_clk_wiz_1_0.xci
# IP: The module: 'Lab7MicroBlaze_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Calypso/Documents/- - - UIUC Academics/Spring 2024/ECE 385/Lab 7/ECE385_Lab7.1/ECE385_Lab7.1.gen/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_clk_wiz_1_0/Lab7MicroBlaze_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7MicroBlaze_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Calypso/Documents/- - - UIUC Academics/Spring 2024/ECE 385/Lab 7/ECE385_Lab7.1/ECE385_Lab7.1.gen/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_clk_wiz_1_0/Lab7MicroBlaze_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7MicroBlaze_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Calypso/Documents/- - - UIUC Academics/Spring 2024/ECE 385/Lab 7/ECE385_Lab7.1/ECE385_Lab7.1.gen/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_clk_wiz_1_0/Lab7MicroBlaze_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7MicroBlaze_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Calypso/Documents/- - - UIUC Academics/Spring 2024/ECE 385/Lab 7/ECE385_Lab7.1/ECE385_Lab7.1.srcs/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_clk_wiz_1_0/Lab7MicroBlaze_clk_wiz_1_0.xci
# IP: The module: 'Lab7MicroBlaze_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Calypso/Documents/- - - UIUC Academics/Spring 2024/ECE 385/Lab 7/ECE385_Lab7.1/ECE385_Lab7.1.gen/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_clk_wiz_1_0/Lab7MicroBlaze_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7MicroBlaze_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Calypso/Documents/- - - UIUC Academics/Spring 2024/ECE 385/Lab 7/ECE385_Lab7.1/ECE385_Lab7.1.gen/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_clk_wiz_1_0/Lab7MicroBlaze_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7MicroBlaze_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Calypso/Documents/- - - UIUC Academics/Spring 2024/ECE 385/Lab 7/ECE385_Lab7.1/ECE385_Lab7.1.gen/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_clk_wiz_1_0/Lab7MicroBlaze_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7MicroBlaze_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
