# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/merli/ECE385Lab7.1/ECE385_Lab7.1/ECE385_Lab7.1.srcs/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_ilmb_v10_1/Lab7MicroBlaze_ilmb_v10_1.xci
# IP: The module: 'Lab7MicroBlaze_ilmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/merli/ECE385Lab7.1/ECE385_Lab7.1/ECE385_Lab7.1.gen/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_ilmb_v10_1/Lab7MicroBlaze_ilmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7MicroBlaze_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/merli/ECE385Lab7.1/ECE385_Lab7.1/ECE385_Lab7.1.srcs/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_ilmb_v10_1/Lab7MicroBlaze_ilmb_v10_1.xci
# IP: The module: 'Lab7MicroBlaze_ilmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/merli/ECE385Lab7.1/ECE385_Lab7.1/ECE385_Lab7.1.gen/sources_1/bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_ilmb_v10_1/Lab7MicroBlaze_ilmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7MicroBlaze_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
