# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab 7/mb_usb_hdmi_top.xdc

# Block Designs: bd/Lab7MicroBlaze/Lab7MicroBlaze.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze || ORIG_REF_NAME==Lab7MicroBlaze} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_xbar_0/Lab7MicroBlaze_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_xbar_0 || ORIG_REF_NAME==Lab7MicroBlaze_xbar_0} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_microblaze_0_axi_periph_0/Lab7MicroBlaze_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Lab7MicroBlaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_microblaze_0_axi_intc_0/Lab7MicroBlaze_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Lab7MicroBlaze_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_mdm_1_0/Lab7MicroBlaze_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_mdm_1_0 || ORIG_REF_NAME==Lab7MicroBlaze_mdm_1_0} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_clk_wiz_1_0/Lab7MicroBlaze_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_clk_wiz_1_0 || ORIG_REF_NAME==Lab7MicroBlaze_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_rst_clk_wiz_1_100M_0/Lab7MicroBlaze_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Lab7MicroBlaze_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_axi_uartlite_0_0/Lab7MicroBlaze_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_axi_uartlite_0_0 || ORIG_REF_NAME==Lab7MicroBlaze_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_microblaze_0_1/Lab7MicroBlaze_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_microblaze_0_1 || ORIG_REF_NAME==Lab7MicroBlaze_microblaze_0_1} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_dlmb_v10_1/Lab7MicroBlaze_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_dlmb_v10_1 || ORIG_REF_NAME==Lab7MicroBlaze_dlmb_v10_1} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_ilmb_v10_1/Lab7MicroBlaze_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_ilmb_v10_1 || ORIG_REF_NAME==Lab7MicroBlaze_ilmb_v10_1} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_dlmb_bram_if_cntlr_1/Lab7MicroBlaze_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==Lab7MicroBlaze_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_ilmb_bram_if_cntlr_1/Lab7MicroBlaze_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==Lab7MicroBlaze_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_lmb_bram_1/Lab7MicroBlaze_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_lmb_bram_1 || ORIG_REF_NAME==Lab7MicroBlaze_lmb_bram_1} -quiet] -quiet

# IP: bd/Lab7MicroBlaze/ip/Lab7MicroBlaze_hdmi_text_controller_1_0/Lab7MicroBlaze_hdmi_text_controller_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7MicroBlaze_hdmi_text_controller_1_0 || ORIG_REF_NAME==Lab7MicroBlaze_hdmi_text_controller_1_0} -quiet] -quiet

# XDC: c:/Users/merli/ECE385Lab7.1/ECE385_Lab7.1/ECE385_Lab7.1.gen/sources_1/bd/Lab7MicroBlaze/Lab7MicroBlaze_ooc.xdc
